name: kayta
version: 1.0.0
description: Package Kayta by Bernardo Veras
homepage: https://vvssistemas.com.br/
author: Bernardo Veras

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2
  auto_size_text: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  faker: ^1.3.0
  test: ^1.15.7
  flutter_test:
    sdk: flutter

flutter: