name: kayta
version: 1.0.0
description: Kayta by Bernardo Veras
homepage: https://vvssistemas.com.br/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: 0.13.0
  auto_size_text: 3.0.0-nullsafety.0
  intl: 0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.12
  faker: 2.0.0-rc.1
  test: 1.16.5
  flutter_test:
    sdk: flutter

flutter: