name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@master

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: "2.2.1"
        channel: "stable"

    - name: Build package
      run: flutter pub get
    
    - name: Test
      run: flutter test --coverage